backend:
  name: github
  repo: kerivin/kerivin.github.io
  branch: master
  base_url: https://sveltia-cms-auth.kerivin-zero.workers.dev
  api_root: https://api.github.com

  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete"{{path}}"
    openAuthoring: '{{message}}'

media_folder: "assets"
site_url: https://kerivin.github.io/
search: false
logo_url: https://kerivin.github.io/favicon.ico

slug:
  encoding: "unicode"

collections:
- name: 'blog'
  label: 'Blog'
  folder: '_posts/'
  create: true
  delete: true
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  editor:
    preview: false
  fields:
    - { name: 'layout', widget: 'hidden', default: 'post' }
    - { name: 'title', widget: 'string' }
    - { name: 'date', widget: 'datetime', picker_utc: true, format: 'YYYY-MM-DD' }
    - { name: 'featured', widget: 'boolean', default: false }
    - { name: 'spoiler', widget: 'boolean', default: false }
    - { name: 'image', widget: 'image', choose_url: 'true' }
    - { name: 'tags', widget: 'string' }
    - { name: 'category', widget: 'string', required: false }
    - { name: 'body', widget: 'markdown' }
